TWILIO_A_KEY: 'ACa7c7ef4ddcd33904e7dcccc69521c5de'
TWILIO_SECRET_KEY: '12f9ad8c08186a0e9817313b26fc5827'

STRIPE_PUBLISHABLE_KEY: 'pk_test_ARJCNc3qk5WszTdbovdFRqw7'
STRIPE_CONNECT_KEY: 'ca_EiZdfWsf6tWr4QKYBJwxv94ZwPhLgbe0'
STRIPE_API_KEY: 'sk_test_dkHPYLDzzZfy59QVTK9CwKCN'
FACEBOOK_ACCESS_ID: '571626849973300'
FACEBOOK_SECRET: 'e397ce4981a9950c0b7865cf7d39b404'


SHAREBNB_DATABASE_PASSWORD: 'GoodLife777'
development:
  # admin_name: First User
  # admin_email: user@example.com
  # admin_password: changeme
  # email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  # email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  # domain_name: example.com
  facebook_access_id: <%= ENV["FACEBOOK_ACCESS_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  # mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_connect_key: <%= ENV["STRIPE_CONNECT_KEY"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  # product_title: <%= ENV["PRODUCT_TITLE"] %>
  # product_price: <%= ENV["PRODUCT_PRICE"] %>
  secret_key_base: 70546d78cea6376de6d693f305c0741583fa923a1cba7ac93c7ad117a41493c15dcdd8d1c7d74a4a790eb43237581bbe6ef4784dbcfa22a2189f06012a86816a

# test:
#   domain_name: example.com 
#   secret_key_base: 2d075dee52a6f35fffad30c615b430bd5c156a87f54914e280497f460cd9f5b2f092a041a4f7f4cec85c4e87cb80d183140c3e2bfa1464b33624a2b04f43a5f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # admin_name: <%= ENV["ADMIN_NAME"] %>
  # admin_email: <%= ENV["ADMIN_EMAIL"] %>
  # admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  # email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  # email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  # domain_name: <%= ENV["DOMAIN_NAME"] %>
  # mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  # mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %> 
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %> 
  facebook_access_id: <%= ENV["FACEBOOK_ACCESS_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  # product_title: <%= ENV["PRODUCT_TITLE"] %> 
  # product_price: <%= ENV["PRODUCT_PRICE"] %> 
  stripe_connect_key: <%= ENV["STRIPE_CONNECT_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postgres_db_password: <%= ENV["SHAREBNB_DATABASE_PASSWORD"] %>
